name: C++ CI for TgBot project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libboost-all-dev libcurl4-openssl-dev \
        libsqlite3-dev nlohmann-json3-dev
        sudo apt-get install -y vcpkg
        ./vcpkg install cpr

    - name: Configure CMake
      run: cmake -B build -S .
      shell: bash
    
    - name: Build Project
      run: cmake --build build
      shell: bash

    - name: Run Tests
      working-directory: ./build
      run: ./untitled
